server:
  port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    peer-node-read-timeout-ms: 5000
    
spring:
  application:
    name: ribbon-example-with-eureka-service
